
final List<String> moodAffectingFactors = [
  'Work-related',
  'Relationship',
  'Family',
  'Finance',
  'Movie',
  'Health',
  'Sleep',
  'Weather',
  'Social Life',
  'Exercise',
  'Education',
  'Work Environment',
  'Friends',
  'Financial Stress',
  'Personal Goals',
  'Hobbies',
  'Social Media',
  'Current Events',
  'Travel',
  'Creativity',
  'Spirituality',
  'Sleep Quality',
  'Diet',
  'Physical Health',
  'Mental Health',
  'Weather',
  'Seasonal Changes',
  'Time Management',
  'Procrastination',
  'Technology/Device Use',
];
